###课程查询
POST {{gateway_host}}/content/course/list?pageNo=1&pageSize=5
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "spring",
  "publishStatus": "203002"
}

<> 2023-03-21T014555.200.json

###课程类别查询
GET {{content_host}}/content/course-category/tree-nodes

###课程新增
POST {{content_host}}/content/course
Content-Type: application/json

{
  "mt": "12001",
  "st": "12010",
  "name": "SpringCloud",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "asda",
  "grade": "204001",
  "description": "",
  "charge": "201001",
  "price": 885,
  "originalPrice":1000,
  "qq": "",
  "wechat": "",
  "phone": "",
  "validDays": 365

}

###课程新增，异常测试
POST {{content_host}}/content/course
Content-Type: application/json

{
  "mt": "12001",
  "st": "12010",
  "name": "exception test",
  "pic": "",
  "teachmode": "200002",
  "users": "exception test",
  "tags": "exception test",
  "grade": "204001",
  "description": "exception test",
  "charge": "201001",
  "price": 0,
  "originalPrice":1000,
  "qq": "exception test",
  "wechat": "exception test",
  "phone": "exception test",
  "validDays": 365

}

###课程查询byId
GET {{gateway_host}}/content/course/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODEzNzkzMTQsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjJlN2VjMWUxLTk4OTYtNGVlZC1hNmE4LWZkZDY5ODAxOTI5YSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.OIS_X4MuSttEOXYJCbO9U_HkAq6RIhrCqZQXdAKXs4s

###课程查询byId
GET {{content_host}}/content/course/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJiaXJ0aGRheVwiOlwiMjAyMi0wOS0yOFQxOToyODo0NlwiLFwiY3JlYXRlVGltZVwiOlwiMjAyMi0wOS0yOFQwODozMjowM1wiLFwiaWRcIjpcIjUwXCIsXCJuYW1lXCI6XCLlrabnlJ8xXCIsXCJuaWNrbmFtZVwiOlwi5aSn5rC054mbXCIsXCJwZXJtaXNzaW9uc1wiOltdLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdHUxXCIsXCJ1c2VycGljXCI6XCJodHRwOi8vZmlsZS54dWVjaGVuZy1wbHVzLmNvbS9kZGRmXCIsXCJ1dHlwZVwiOlwiMTAxMDAxXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4MTM5MzU3OCwiYXV0aG9yaXRpZXMiOlsicDEiXSwianRpIjoiMDBiZTJmZTYtZjE4Yy00ZWRhLTg5ZDEtMjMwYmNjYjBiMGExIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.j2u0jWs66lVxlya7iVP0lGGcMPvOxrC20NZZw__2SeQ

###课程修改
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "id": 86,
  "mt": "12001",
  "st": "12010",
  "name": "xiugai",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "asda",
  "grade": "204001",
  "description": "",
  "charge": "201001",
  "price": 885,
  "originalPrice":1000,
  "qq": "",
  "wechat": "",
  "phone": "",
  "validDays": 365

}

###课程计划查询byCourseId
GET {{gateway_host}}/content/teachplan/117/tree-nodes

###
POST {{gateway_host}}/content/courseaudit/commit/1
