###
POST {{content_host}}/content/course/list?pageNo=1&pageSize=5
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "spring",
  "publishStatus": "203002"
}

<> 2023-03-21T014555.200.json

###
GET {{content_host}}/content/course-category/tree-nodes
